name: opentelemetry-demo-recommendationservice
service:
  name: opentelemetry-demo-recommendationservice
  type: ClusterIP
  port: 8080
  targetPort: 8080
selectorLabels:
  opentelemetry.io/name: opentelemetry-demo-recommendationservice
templateLabels:
  opentelemetry.io/name: opentelemetry-demo-recommendationservice
  app.kubernetes.io/instance: opentelemetry-demo
  app.kubernetes.io/component: recommendationservice
  app.kubernetes.io/name: opentelemetry-demo-recommendationservice
replicaCount: 2
serviceAccountName: opentelemetry-demo
image:
  repository: ghcr.io/open-telemetry/demo
  tag: 1.12.0-recommendationservice
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 500Mi
env:
- name: OTEL_SERVICE_NAME
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: metadata.labels['app.kubernetes.io/component']
- name: OTEL_COLLECTOR_NAME
  value: opentelemetry-demo-otelcol
- name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
  value: cumulative
- name: RECOMMENDATION_SERVICE_PORT
  value: '8080'
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: opentelemetry-demo-productcatalogservice:8080
- name: OTEL_PYTHON_LOG_CORRELATION
  value: 'true'
- name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
  value: python
- name: FLAGD_HOST
  value: opentelemetry-demo-flagd
- name: FLAGD_PORT
  value: '8013'
- name: OTEL_EXPORTER_OTLP_ENDPOINT
  value: http://$(OTEL_COLLECTOR_NAME):4317
- name: OTEL_RESOURCE_ATTRIBUTES
  value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=1.12.0
volumeMounts: []
initContainers: []
volumes: []
readinessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
livenessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 5
ingress:
  enabled: false
  annotations: {}
  spec: {}
configMaps: []
