name: opentelemetry-demo-valkey
service:
  name: opentelemetry-demo-valkey
  type: ClusterIP
  port: 6379
  targetPort: 6379
selectorLabels:
  opentelemetry.io/name: opentelemetry-demo-valkey
templateLabels:
  opentelemetry.io/name: opentelemetry-demo-valkey
  app.kubernetes.io/instance: opentelemetry-demo
  app.kubernetes.io/component: valkey
  app.kubernetes.io/name: opentelemetry-demo-valkey
replicaCount: 2
serviceAccountName: opentelemetry-demo
image:
  repository: valkey/valkey
  tag: 7.2-alpine
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: 50m
    memory: 10Mi
  limits:
    cpu: 200m
    memory: 20Mi
env:
- name: OTEL_SERVICE_NAME
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: metadata.labels['app.kubernetes.io/component']
- name: OTEL_COLLECTOR_NAME
  value: opentelemetry-demo-otelcol
- name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
  value: cumulative
- name: OTEL_RESOURCE_ATTRIBUTES
  value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=1.12.0
volumeMounts: []
initContainers: []
volumes: []
readinessProbe:
  tcpSocket:
    port: 6379
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
livenessProbe:
  tcpSocket:
    port: 6379
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 5
ingress:
  enabled: false
  annotations: {}
  spec: {}
configMaps: []
