name: opentelemetry-demo-loadgenerator
service:
  name: opentelemetry-demo-loadgenerator
  type: ClusterIP
  port: 8089
  targetPort: 8089
selectorLabels:
  opentelemetry.io/name: opentelemetry-demo-loadgenerator
templateLabels:
  opentelemetry.io/name: opentelemetry-demo-loadgenerator
  app.kubernetes.io/instance: opentelemetry-demo
  app.kubernetes.io/component: loadgenerator
  app.kubernetes.io/name: opentelemetry-demo-loadgenerator
replicaCount: 2
serviceAccountName: opentelemetry-demo
image:
  repository: ghcr.io/open-telemetry/demo
  tag: 1.12.0-loadgenerator
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: 500m
    memory: 1024Mi
  limits:
    cpu: 1000m
    memory: 1500Mi
env:
- name: OTEL_SERVICE_NAME
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: metadata.labels['app.kubernetes.io/component']
- name: OTEL_COLLECTOR_NAME
  value: opentelemetry-demo-otelcol
- name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
  value: cumulative
- name: LOCUST_WEB_PORT
  value: '8089'
- name: LOCUST_USERS
  value: '10'
- name: LOCUST_SPAWN_RATE
  value: '1'
- name: LOCUST_HOST
  value: http://opentelemetry-demo-frontendproxy:8080
- name: LOCUST_HEADLESS
  value: 'false'
- name: LOCUST_AUTOSTART
  value: 'true'
- name: LOCUST_BROWSER_TRAFFIC_ENABLED
  value: 'true'
- name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
  value: python
- name: FLAGD_HOST
  value: opentelemetry-demo-flagd
- name: FLAGD_PORT
  value: '8013'
- name: OTEL_EXPORTER_OTLP_ENDPOINT
  value: http://$(OTEL_COLLECTOR_NAME):4317
- name: OTEL_RESOURCE_ATTRIBUTES
  value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=1.12.0
volumeMounts: []
initContainers: []
volumes: []
readinessProbe:
  tcpSocket:
    port: 8089
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
livenessProbe:
  tcpSocket:
    port: 8089
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 5
ingress:
  enabled: false
  annotations: {}
  spec: {}
configMaps: []
